### ISSUE TITLE
struct.error: argument for 's' must be a string

### ISSUE THREAD

**Issue by Skeiceee** [rissole/srcds-web-manager#1]
Traceback (most recent call last):
  File "app.py", line 34, in <module>
    refresh_rcons();
  File "app.py", line 29, in refresh_rcons
    servers_config.get(section, 'password', '')
  File "/usr/local/lib/python2.7/dist-packages/srcds/rcon.py", line 59, in __init__
    self._authenticate(password)
  File "/usr/local/lib/python2.7/dist-packages/srcds/rcon.py", line 64, in _authenticate
    self._send_pkt(auth_pkt)
  File "/usr/local/lib/python2.7/dist-packages/srcds/rcon.py", line 97, in _send_pkt
    data = pkt.pack()
  File "/usr/local/lib/python2.7/dist-packages/srcds/rcon.py", line 37, in pack
    bytearray(body_str, 'utf-8'))
struct.error: argument for 's' must be a string

Any idea why this happens?

**Comment by Skeiceee** [comment]
![image](https://user-images.githubusercontent.com/12854219/71703745-169deb00-2db5-11ea-87c8-aadc9185dc04.png)

Tryed to force the string conversion
